Support oprional compress for SSHContext
deepmodeling/dpdispatcher pull request #230
Opened 2022-08-23 23:20 UTC by HuangJiameng

For a large number of small files, compression can be very CPU-intensive and time-consuming. See https://github.com/deepmodeling/dpgen/issues/766. 
Add `tar_compress` in dict `remote_profile`. The archive will be compressed in upload and download if it is True. If not, compression will be skipped.

2022-08-23 23:38 UTC, njzjz requested changes
Codecov's report shows the new case is not covered. Please add a test for the new case into [test_ssh_context.py](https://github.com/deepmodeling/dpdispatcher/blob/master/tests/test_ssh_context.py)

2022-08-23 23:38 UTC, njzjz commented on dpdispatcher/ssh_context.py
> +                        compress=self.tar_compress,
This option is used for OpenSSH compression but not "tar". See also:
- https://man.openbsd.org/ssh#C
- https://man.openbsd.org/ssh_config.5#Compression

2022-08-24 08:15 UTC, HuangJiameng commented
> Codecov's report shows the new case is not covered. Please add a test for the new case into [test_ssh_context.py](https://github.com/deepmodeling/dpdispatcher/blob/master/tests/test_ssh_context.py)

Done.

2022-08-26 03:52 UTC, njzjz commented on tests/test_ssh_context.py
> +        self.machine["remote_profile"]["tar_compress"] = False
`self.machine` is an object of `Machine`. See line 76.

2022-08-29 06:08 UTC, njzjz commented on tests/test_ssh_context.py
> +        self.machine.context.remote_profile['tar_compress'] = False
This is not correct for the following reason:
- `self.machine` is defined in the `setUpClass` and this only executes once for the entire class. When you change the object from `setUpClass`,  other test methods will be affected.
- `remote_profile` is only used to initialize the `SSHSession`. See:
https://github.com/deepmodeling/dpdispatcher/blob/3ec2e4a4d933093b3eedd4092f8f5d2069a84d15/dpdispatcher/ssh_context.py#L300

2022-08-30 01:51 UTC, njzjz commented
`self.context` is defined as `self.__class__.machine.context`, so your change does nothing. It's better to create a new Test class.

2022-08-30 02:48 UTC, njzjz approved these changes

2022-08-30 02:49 UTC, merged