add new batch_type Fugaku
deepmodeling/dpdispatcher pull request #351
Opened 2023-07-07 16:05 UTC by chouyoudou

Added a new batch type for use on Fugaku, a supercomputer using Fujitsu's unique job scheduler.
It has been tested on Dpgen for 20 iterations and no problems have been found.
Also uploaded JSON files for both local and ssh cases.

2023-07-07 17:46 UTC, njzjz requested changes

2023-07-07 17:46 UTC, njzjz commented on dpdispatcher/__init__.py
> +from .fugaku import Fugaku
`Fugaku` should be added to `__all__`.

2023-07-07 17:46 UTC, njzjz commented on dpdispatcher/fugaku.py
Documentation for the new batch type should be added here: https://github.com/deepmodeling/dpdispatcher/blob/master/doc/batch.md

2023-07-08 02:33 UTC, chouyoudou reviewed
```Fugaku``` was added to ```__all__``` now.
Documentation for Fugaku was added in batch.md.

2023-07-09 19:52 UTC, njzjz approved these changes

2023-07-09 20:05 UTC, merged