add "JH_UniScheduler" batch_type
deepmodeling/dpdispatcher pull request #459
Opened 2024-05-21 07:07 UTC by WangSimin123456

JH UniScheduler was developed by JHINNO company. JH UniScheduler is a commercial software and uses "jsub" to submit tasks. Its overall architecture is similar to that of IBM's LSF. However, there are still some differences between them.

2024-05-21 22:21 UTC, njzjz requested changes
Please fix all tests

2024-05-21 22:21 UTC, njzjz commented on doc/index.rst
Please also add documentation to `doc/batch.md`.

2024-05-21 22:21 UTC, njzjz commented on dpdispatcher/machines/JH_UniScheduler.py
> +        ]
This suggestion should be committed.

2024-05-21 22:21 UTC, njzjz commented on tests/devel_test_JH_UniScheduler.py
> +
Did you actually run this file?

2024-05-21 22:21 UTC, njzjz commented on tests/test_JH_UniScheduler_script_generation.py
> +        with open("jsons/machine_lazy_local_JH_UniScheduler.json") as f:
It seems this file doesn't exist

2024-05-25 09:37 UTC, WangSimin123456 commented
> Please fix all tests

Thank you for your comment. It already says "All checks have passed". Can we merge this branch and close this issue? Or what should be done next?

2024-05-25 09:38 UTC, WangSimin123456 commented
> Please fix all tests

Thank you for your comment. It already says "All checks have passed". Can we merge this branch and close this issue? Or what should be done next?

2024-05-26 23:18 UTC, njzjz approved these changes

2024-05-26 23:19 UTC, merged