use dlog to print debug information
deepmodeling/dpdispatcher pull request #53
Opened 2021-06-11 16:34 UTC by felix5572

use dlog to print debug information

2021-06-11 16:55 UTC, njzjz requested changes
Can you look at the output of the GitHub Actions? There are still some outputs produced by `print`.

2021-06-11 16:56 UTC, njzjz commented
https://github.com/deepmodeling/dpdispatcher/pull/53/checks?check_run_id=2804850634#step:5:67

2021-06-12 03:47 UTC, felix5572 commented
And if we cloud recover support for python==3.6 ?  I realize that there are many python3.6 here. and  dpdispatcher can not be installed if python_requires="~=3.7".

2021-06-12 08:02 UTC, njzjz commented on dpdispatcher/dp_cloud_server.py
> +        dlog.debug('debug: check_status', job)
I think dlog doesn't support multiple args. Please check it.

2021-06-12 08:02 UTC, njzjz commented on dpdispatcher/base_context.py
> +            print('KeyError:context_type;subclasses_dict', context_type, cls.subclasses_dict)
You may try `dlog.error` or `dlog.exception`.

2021-06-12 11:04 UTC, felix5572 commented
fixed @njzjz  dlog

2021-06-12 11:06 UTC, felix5572 commented
@njzjz  and fixed. query database in submitting jobs. dpdispatcher will now query database after submitting all the jobs
![image](https://user-images.githubusercontent.com/32410372/121773804-fa5ccb00-cbb0-11eb-9115-1f4368fefaa3.png)

2021-06-12 11:08 UTC, njzjz approved these changes
I will approve after fixing these two

2021-06-12 11:08 UTC, njzjz commented on dpdispatcher/base_context.py
> +            dlog.error("KeyError:context_type; context_type:{context_type}; cls.subclasses_dict:{cls.subclasses_dict}")
```suggestion
            dlog.error(f"KeyError:context_type; context_type:{context_type}; cls.subclasses_dict:{cls.subclasses_dict}")
```

2021-06-12 11:08 UTC, njzjz commented on dpdispatcher/machine.py
> +            dlong.error("KeyError:batch_type; cls.subclasses_dict:{cls.subclasses_dict}; batch_type:{batch_type};")
```suggestion
            dlong.error(f"KeyError:batch_type; cls.subclasses_dict:{cls.subclasses_dict}; batch_type:{batch_type};")
```

2021-06-12 17:22 UTC, njzjz approved these changes

2021-06-14 05:17 UTC, merged