fix bug; will not tag job_tag_finished if one of the tasks fail
deepmodeling/dpdispatcher pull request #64
Opened 2021-06-16 08:00 UTC by felix5572

fix bug; will not tag job_tag_finished if one of the tasks fail

2021-06-16 08:02 UTC, felix5572 commented
@Cloudac7  have a look?

2021-06-16 10:01 UTC, njzjz approved these changes

2021-06-16 10:03 UTC, njzjz requested changes

2021-06-16 10:03 UTC, njzjz commented on dpdispatcher/machine.py
> +export FLAG_TASK_FAIL=0
I think we don't need `export` here, as we only use it in this script.
```suggestion
FLAG_TASK_FAIL=0
```

2021-06-16 10:04 UTC, njzjz requested changes

2021-06-16 10:04 UTC, njzjz commented on dpdispatcher/machine.py
>  export REMOTE_ROOT={remote_root}
```suggestion
REMOTE_ROOT={remote_root}
```

2021-06-17 04:16 UTC, felix5572 commented
@njzjz  I found that the variable in parent shell cannot be accessed by child shell. 
So I change the implementation, we use a new file to record whether the task fails.

2021-06-17 05:16 UTC, merged